# Generated by Django 5.1.7 on 2026-07-08 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('DOZEN', 'Dozen'), ('GRAM', 'Gram')], default='KG', max_length=10),
        ),
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stock', to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'date')},
            },
        ),
    ]
