# Generated by Django 5.1.7 on 2026-07-18 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vote_count', models.IntegerField(default=0)),
                ('poll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_votes', to='shop.pollitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer')),
                ('voted_items', models.ManyToManyField(to='shop.pollitem')),
            ],
        ),
    ]
