# Generated by Django 5.1.7 on 2026-07-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pollitem_dailyvote_uservote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyvote',
            unique_together={('pincode', 'poll_item', 'date')},
        ),
    ]
