# Generated by Django 5.1.7 on 2026-08-26 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
        ('shop', '0008_tokentransaction_tokenwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_update_logs', to='authentication.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
